"""Current structure-aware domain-adaptation building blocks."""

from .backbone import StructureBackbone, StructureBackboneOutput
from .decomposition import DecompositionOutput, SymmetricTimeKernelDecomposition
from .diagnostics import (
    ContributionDiagnostics,
    DecompositionDiagnostics,
    DiagnosticMoments,
    DiagnosticStat,
    compute_decomposition_diagnostics,
    compute_structure_contribution_diagnostics,
    merge_contribution_diagnostics,
    merge_decomposition_diagnostics,
    summarize_contribution_diagnostics,
    summarize_decomposition_diagnostics,
)
from .eden_alignment import (
    EDENDomainAlignmentOutput,
    EDENDomainDiscriminator,
    EDENFusedFeatureAlignment,
    WarmStartGradientReverseLayer,
)
from .full_model import (
    StructureAwareDomainAdaptationModel,
    StructureAwareForwardOutput,
    StructureAwareGeometryOutput,
)
from .joint_trainer import (
    JointStructureDADiagnostics,
    JointStructureDALossOutput,
    JointStructureDATrainStepOutput,
    JointStructureDATrainingConfig,
    create_joint_structure_da_train_loaders,
    joint_structure_da_train_step,
    resolve_domain_score_weight,
    resolve_grl_warmup_max_iters,
    resolve_steps_per_epoch,
    train_joint_structure_da,
    validation_structure_contributions,
)
from .quality_fusion import (
    ComponentQualityBundle,
    HierarchicalQualityFusion,
    HierarchicalQualityObjective,
    HierarchicalQualityOutput,
    QualityLossOutput,
    QualityScoreOutput,
    QualityScorer,
    StructuralQualityBundle,
    concatenate_hierarchical_quality_outputs,
)
from .representation import (
    PairedStructureFeatures,
    QualityAwareClassifierOutput,
    QualityAwareComponentClassifier,
)
from .temporal_coordinates import (
    TemporalCoordinateOutput,
    TemporalShapePhaseCoordinates,
)
from .temporal_functional import (
    SourceRunningStandardizer,
    TemporalFunctionalLift,
    TemporalFunctionalOutput,
)
from .temporal_geometry import (
    PhaseTangentOutput,
    TemporalGeometryLossOutput,
    TemporalGeometryObjective,
    warp_to_identity_tangent,
)
from .temporal_head import (
    PhaseCoordinateEncoder,
    ShapeCoordinateEncoder,
    TemporalStructureEncoder,
    TemporalStructureFeatureOutput,
    TemporalStructureOutputHead,
)
from .temporal_module import (
    SharedTemporalStructureOperator,
    TemporalGeometryForwardOutput,
    TemporalGeometryPairOutput,
    TemporalStructureExtractor,
    TemporalStructureOutput,
    TemporalStructurePairOutput,
    TrendStructureTemporalCore,
    TrendStructureTemporalCoreOutput,
)
from .temporal_registration import (
    MonotoneWarpCandidatesOutput,
    MonotoneWarpEstimator,
    MonotoneWarpOutput,
    SourceRunningSRVFTemplate,
    SourceSRVFTemplateOutput,
    TemporalRegistrationOutput,
    TemporalSRVFRegistration,
    invert_monotone_warp,
    select_warp_candidate,
)
from .temporal_selection import (
    TrendStructurePhaseSelectionOutput,
    TrendStructureSelectionConfig,
    select_trend_structure_phase,
)
from .temporal_srvf import (
    SourceRunningSupportScale,
    TemporalSRVFExtractor,
    TemporalSRVFOutput,
)

__all__ = [
    "ComponentQualityBundle",
    "ContributionDiagnostics",
    "DecompositionOutput",
    "DecompositionDiagnostics",
    "DiagnosticMoments",
    "DiagnosticStat",
    "EDENDomainAlignmentOutput",
    "EDENDomainDiscriminator",
    "EDENFusedFeatureAlignment",
    "HierarchicalQualityFusion",
    "HierarchicalQualityObjective",
    "HierarchicalQualityOutput",
    "JointStructureDALossOutput",
    "JointStructureDADiagnostics",
    "JointStructureDATrainStepOutput",
    "JointStructureDATrainingConfig",
    "MonotoneWarpCandidatesOutput",
    "MonotoneWarpEstimator",
    "MonotoneWarpOutput",
    "PairedStructureFeatures",
    "PhaseCoordinateEncoder",
    "PhaseTangentOutput",
    "QualityAwareClassifierOutput",
    "QualityAwareComponentClassifier",
    "QualityLossOutput",
    "QualityScoreOutput",
    "QualityScorer",
    "ShapeCoordinateEncoder",
    "SharedTemporalStructureOperator",
    "SourceRunningSRVFTemplate",
    "SourceRunningStandardizer",
    "SourceRunningSupportScale",
    "SourceSRVFTemplateOutput",
    "StructuralQualityBundle",
    "StructureAwareDomainAdaptationModel",
    "StructureAwareForwardOutput",
    "StructureAwareGeometryOutput",
    "StructureBackbone",
    "StructureBackboneOutput",
    "SymmetricTimeKernelDecomposition",
    "TemporalCoordinateOutput",
    "TemporalFunctionalLift",
    "TemporalFunctionalOutput",
    "TemporalGeometryForwardOutput",
    "TemporalGeometryLossOutput",
    "TemporalGeometryObjective",
    "TemporalGeometryPairOutput",
    "TemporalRegistrationOutput",
    "TemporalSRVFExtractor",
    "TemporalSRVFOutput",
    "TemporalSRVFRegistration",
    "TemporalShapePhaseCoordinates",
    "TemporalStructureEncoder",
    "TemporalStructureExtractor",
    "TemporalStructureFeatureOutput",
    "TemporalStructureOutput",
    "TemporalStructureOutputHead",
    "TemporalStructurePairOutput",
    "TrendStructureTemporalCore",
    "TrendStructureTemporalCoreOutput",
    "TrendStructurePhaseSelectionOutput",
    "TrendStructureSelectionConfig",
    "WarmStartGradientReverseLayer",
    "concatenate_hierarchical_quality_outputs",
    "compute_decomposition_diagnostics",
    "compute_structure_contribution_diagnostics",
    "create_joint_structure_da_train_loaders",
    "joint_structure_da_train_step",
    "invert_monotone_warp",
    "merge_contribution_diagnostics",
    "merge_decomposition_diagnostics",
    "resolve_domain_score_weight",
    "resolve_grl_warmup_max_iters",
    "resolve_steps_per_epoch",
    "select_warp_candidate",
    "select_trend_structure_phase",
    "train_joint_structure_da",
    "summarize_contribution_diagnostics",
    "summarize_decomposition_diagnostics",
    "validation_structure_contributions",
    "warp_to_identity_tangent",
]
