"""Two-stage structure model: Stage-1 source prototype training backbone."""

from models.ltae import ContinuousTime2Vec, TrendStructureSharedLTAE

from .backbone import StructureBackbone, StructureBackboneOutput
from .decomposition import DecompositionOutput, SymmetricTimeKernelDecomposition
from .diagnostics import (
    ContributionDiagnostics,
    DecompositionDiagnostics,
    DiagnosticMoments,
    DiagnosticStat,
    compute_decomposition_diagnostics,
    compute_structure_contribution_diagnostics,
    merge_contribution_diagnostics,
    merge_decomposition_diagnostics,
    summarize_contribution_diagnostics,
    summarize_decomposition_diagnostics,
)
from .feature_snapshots import (
    FeatureSnapshotConfig,
    FeatureSnapshotManager,
    SnapshotCaptureResult,
    create_feature_snapshot_manager,
    deterministic_class_selection,
    load_selected_samples,
)
from .full_model import TSStructureModel
from .phase_evidence import (
    GammaDiagnostics,
    PairwisePhaseCandidate,
    compute_gamma_diagnostics,
    empirical_cdf,
    shape_distance_to_prototype,
)
from .phase_geometry import (
    gamma_to_psi,
    pairwise_phase_distances,
    phase_distance,
    sqrt_mean_gamma,
    sqrt_median_gamma,
)
from .domain_phase_state import (
    CandidatePhaseCompatibility,
    CandidatePhaseCompatibilityStatus,
    DomainPhaseConfig,
    DomainPhaseState,
    PhaseClassCenter,
    PhaseDecisionStatus,
    PhaseGroup,
    PhaseGroupStatus,
    ResidualPhaseEvidence,
    ResidualPhaseGroupCandidate,
    collect_residual_phase_evidence,
    detect_residual_phase_group,
    evaluate_candidate_phase_compatibility,
    evaluate_sample_class_phase_compatibility,
    update_domain_phase_state,
)
from .domain_shape_state import (
    DomainShapeConfig,
    DomainShapeState,
    DomainShapeStatus,
    TargetShapeClassCenter,
    update_domain_shape_state,
)
from .confirmed_phase_view import (
    IDENTITY_PHASE_GROUP_ID,
    ConfirmedPhaseView,
    align_target_positions_to_source,
    build_confirmed_class_to_group_map,
    build_confirmed_phase_view,
    build_phase_calibrated_view,
)
from .ema_teacher import Stage2EMATeacher
from .phase_registration import (
    FdasrsfCurveRegistrationAdapter,
    GammaLegalityOutput,
    build_source_registration_prototypes,
    check_gamma_legality,
    resample_gamma,
    warp_q_gamma,
    warp_support_gamma,
)
from .prototype_bank import (
    QUANTILE_LEVELS,
    SourcePrototypeBank,
    SupportAwareDistanceOutput,
    support_aware_q_distance,
)
from .registration_geometry import (
    RegistrationGeometryOutput,
    SourceRegistrationPrototypeBank,
    TargetGeometryCache,
    evaluate_registration_geometry,
)
from .representation import (
    FunctionalGeometryOutput,
    RawTemporalRepresentation,
    TSStructureForwardOutput,
)
from .source_prototype_scanner import (
    build_source_prototype_bank,
    finalize_distance_statistics,
    refresh_source_fused_statistics,
)
from .source_trainer import SourceClassificationTrainer, SourceTrainStepOutput
from .stage1_objective import Stage1LossOutput, Stage1Objective
from .stage2_trainer import (
    DeviceBatchLoader,
    Stage2RunResult,
    Stage2StatisticsSnapshot,
    Stage2Trainer,
    Stage2TrainerConfig,
    TargetHypothesisCache,
    build_stage2_registration_extractor,
    run_stage2_statistics_diagnostic,
    run_stage2_training,
)
from .stage2_parameter_policy import (
    Stage2ParameterPolicy,
    configure_stage2_parameter_policy,
)
from .stage2_objective import (
    Stage2Objective,
    Stage2ObjectiveConfig,
    Stage2ObjectiveOutput,
)
from .shape_transport import (
    SyntheticSourceDiagnostics,
    SyntheticSourceExample,
    apply_domain_shape_effect,
    build_phase_only_synthetic_source_example,
    build_synthetic_source_example,
    correct_target_shape_to_source,
    evaluate_synthetic_source_diagnostics,
    inverse_vector_srvf,
    map_source_positions_to_target,
    synthesize_source_shape_to_target,
)
from .stable_target_labels import (
    StableLabelConfig,
    StableTargetCandidate,
    StableTargetLabel,
    StableTargetLabelScanResult,
    evaluate_stable_target_candidate,
    scan_stable_target_labels,
    scan_stable_target_labels_from_candidates,
    scan_stable_target_labels_from_confirmed_phase,
)
from .target_hypothesis_scan import (
    CandidatePseudoLabel,
    PairwiseClassAlignment,
    PhaseHypothesisScanConfig,
    TargetClassPhaseHypothesis,
    TargetHypothesisScanResult,
    TargetPhaseHypothesisScanner,
    scan_target_class_phase_hypotheses,
)
from .temporal_functional import (
    SourceRunningStandardizer,
    TemporalFunctionalLift,
    TemporalFunctionalOutput,
)
from .temporal_geometry import PhaseTangentOutput, warp_to_identity_tangent
from .temporal_head import SharedTrendStructureLTAE
from .temporal_module import TrendStructureTemporalModule
from .temporal_srvf import (
    SourceRunningSupportScale,
    TemporalSRVFExtractor,
    TemporalSRVFOutput,
)

__all__ = [
    "QUANTILE_LEVELS",
    "ContinuousTime2Vec",
    "ContributionDiagnostics",
    "ConfirmedPhaseView",
    "IDENTITY_PHASE_GROUP_ID",
    "DecompositionDiagnostics",
    "DecompositionOutput",
    "DomainPhaseConfig",
    "DomainPhaseState",
    "DomainShapeConfig",
    "DomainShapeState",
    "DomainShapeStatus",
    "DiagnosticMoments",
    "DiagnosticStat",
    "FdasrsfCurveRegistrationAdapter",
    "FeatureSnapshotConfig",
    "FeatureSnapshotManager",
    "FunctionalGeometryOutput",
    "GammaDiagnostics",
    "GammaLegalityOutput",
    "PairwisePhaseCandidate",
    "PairwiseClassAlignment",
    "CandidatePseudoLabel",
    "CandidatePhaseCompatibility",
    "CandidatePhaseCompatibilityStatus",
    "PhaseHypothesisScanConfig",
    "PhaseClassCenter",
    "PhaseDecisionStatus",
    "PhaseGroup",
    "PhaseGroupStatus",
    "ResidualPhaseEvidence",
    "ResidualPhaseGroupCandidate",
    "PhaseTangentOutput",
    "RawTemporalRepresentation",
    "RegistrationGeometryOutput",
    "SharedTrendStructureLTAE",
    "SnapshotCaptureResult",
    "SourceClassificationTrainer",
    "SourcePrototypeBank",
    "SourceRegistrationPrototypeBank",
    "SourceRunningStandardizer",
    "SourceRunningSupportScale",
    "SourceTrainStepOutput",
    "StableLabelConfig",
    "StableTargetCandidate",
    "StableTargetLabel",
    "StableTargetLabelScanResult",
    "scan_stable_target_labels_from_confirmed_phase",
    "scan_stable_target_labels_from_candidates",
    "Stage1LossOutput",
    "Stage1Objective",
    "Stage2EMATeacher",
    "Stage2Objective",
    "Stage2ObjectiveConfig",
    "Stage2ObjectiveOutput",
    "Stage2ParameterPolicy",
    "StructureBackbone",
    "StructureBackboneOutput",
    "SupportAwareDistanceOutput",
    "SyntheticSourceDiagnostics",
    "SyntheticSourceExample",
    "SymmetricTimeKernelDecomposition",
    "TSStructureForwardOutput",
    "TSStructureModel",
    "TargetClassPhaseHypothesis",
    "TargetGeometryCache",
    "TargetHypothesisScanResult",
    "TargetPhaseHypothesisScanner",
    "TargetShapeClassCenter",
    "TemporalFunctionalLift",
    "TemporalFunctionalOutput",
    "TemporalSRVFExtractor",
    "TemporalSRVFOutput",
    "TrendStructureSharedLTAE",
    "TrendStructureTemporalModule",
    "apply_domain_shape_effect",
    "build_source_prototype_bank",
    "build_synthetic_source_example",
    "build_source_registration_prototypes",
    "build_confirmed_class_to_group_map",
    "build_confirmed_phase_view",
    "build_phase_calibrated_view",
    "check_gamma_legality",
    "compute_decomposition_diagnostics",
    "compute_gamma_diagnostics",
    "compute_structure_contribution_diagnostics",
    "collect_residual_phase_evidence",
    "correct_target_shape_to_source",
    "configure_stage2_parameter_policy",
    "create_feature_snapshot_manager",
    "detect_residual_phase_group",
    "deterministic_class_selection",
    "empirical_cdf",
    "evaluate_candidate_phase_compatibility",
    "evaluate_sample_class_phase_compatibility",
    "evaluate_registration_geometry",
    "evaluate_stable_target_candidate",
    "evaluate_synthetic_source_diagnostics",
    "finalize_distance_statistics",
    "gamma_to_psi",
    "inverse_vector_srvf",
    "load_selected_samples",
    "map_source_positions_to_target",
    "merge_contribution_diagnostics",
    "merge_decomposition_diagnostics",
    "pairwise_phase_distances",
    "phase_distance",
    "resample_gamma",
    "scan_target_class_phase_hypotheses",
    "scan_stable_target_labels",
    "shape_distance_to_prototype",
    "sqrt_mean_gamma",
    "sqrt_median_gamma",
    "summarize_contribution_diagnostics",
    "summarize_decomposition_diagnostics",
    "synthesize_source_shape_to_target",
    "support_aware_q_distance",
    "warp_q_gamma",
    "warp_support_gamma",
    "warp_to_identity_tangent",
    "update_domain_phase_state",
    "update_domain_shape_state",
    "align_target_positions_to_source",
    "build_phase_only_synthetic_source_example",
    "build_stage2_registration_extractor",
    "DeviceBatchLoader",
    "refresh_source_fused_statistics",
    "run_stage2_statistics_diagnostic",
    "run_stage2_training",
    "Stage2RunResult",
    "Stage2StatisticsSnapshot",
    "Stage2Trainer",
    "Stage2TrainerConfig",
    "TargetHypothesisCache",
]
