"""TimeMatch-style Stage-2 objective for TSStructure.

The Student is optimized from exactly two semantic branches:

1. target-style source samples carrying true source labels;
2. native target samples carrying stop-gradient Stable Labels.

Domain Phase is used to construct supervision or target-style source
inputs. They are not additional differentiable losses in this objective.
"""

from __future__ import annotations

from dataclasses import dataclass
import math

import torch
from torch import Tensor, nn

from utils.focal_loss import FocalLoss


@dataclass(frozen=True)
class Stage2ObjectiveConfig:
    """Training weights matching the TimeMatch Stage-2 topology."""

    lambda_target: float = 1.0
    focal_gamma: float = 1.0

    def __post_init__(self) -> None:
        if not math.isfinite(float(self.lambda_target)) or float(self.lambda_target) < 0.0:
            raise ValueError("lambda_target must be finite and non-negative")
        if not math.isfinite(float(self.focal_gamma)) or float(self.focal_gamma) < 0.0:
            raise ValueError("focal_gamma must be finite and non-negative")


@dataclass(frozen=True)
class Stage2ObjectiveOutput:
    total: Tensor
    source_to_target: Tensor
    native_target: Tensor
    source_count: int
    target_count: int


def _zero_like(reference: Tensor) -> Tensor:
    return reference.sum() * 0.0


class Stage2Objective(nn.Module):
    """Compute the formal TimeMatch-style TSStructure Stage-2 objective.

    ``source_to_target_logits`` are produced from source examples transported
    toward the target domain by confirmed Phase/Shape statistics and keep their
    true source labels. ``native_target_logits`` are produced from *native target
    temporal positions* and use Stable Labels generated by the EMA Teacher.
    """

    def __init__(
        self,
        *,
        num_classes: int,
        config: Stage2ObjectiveConfig,
    ) -> None:
        super().__init__()
        if isinstance(num_classes, bool) or not isinstance(num_classes, int) or num_classes < 2:
            raise ValueError("num_classes must be an integer >= 2")
        if not isinstance(config, Stage2ObjectiveConfig):
            raise TypeError("config must be a Stage2ObjectiveConfig")
        self.num_classes = num_classes
        self.config = config
        self.criterion = FocalLoss(gamma=float(config.focal_gamma))

    def _validate_logits_labels(
        self,
        logits: Tensor,
        labels: Tensor,
        *,
        prefix: str,
    ) -> None:
        if logits.ndim != 2 or logits.shape[1] != self.num_classes:
            raise ValueError(f"{prefix}_logits must have shape [B,C]")
        if labels.shape != (logits.shape[0],):
            raise ValueError(f"{prefix}_labels must have shape [B]")
        if labels.dtype != torch.long:
            raise ValueError(f"{prefix}_labels must use torch.long dtype")

    def forward(
        self,
        *,
        source_to_target_logits: Tensor,
        source_labels: Tensor,
        native_target_logits: Tensor | None = None,
        stable_target_labels: Tensor | None = None,
    ) -> Stage2ObjectiveOutput:
        self._validate_logits_labels(
            source_to_target_logits,
            source_labels,
            prefix="source_to_target",
        )
        if source_to_target_logits.shape[0] == 0:
            raise ValueError("Stage-2 source-to-target branch cannot be empty")

        source_loss = self.criterion(source_to_target_logits, source_labels)
        source_count = int(source_to_target_logits.shape[0])

        target_present = (
            native_target_logits is not None
            and int(native_target_logits.shape[0]) > 0
        )
        if not target_present:
            if stable_target_labels is not None and stable_target_labels.numel() > 0:
                raise ValueError(
                    "stable_target_labels require non-empty native_target_logits"
                )
            target_loss = _zero_like(source_to_target_logits)
            target_count = 0
        else:
            if stable_target_labels is None:
                raise ValueError(
                    "native_target_logits require Stable Labels"
                )
            self._validate_logits_labels(
                native_target_logits,
                stable_target_labels,
                prefix="native_target",
            )
            target_count = int(native_target_logits.shape[0])
            target_loss = self.criterion(
                native_target_logits,
                stable_target_labels.detach(),
            )

        total = source_loss + float(self.config.lambda_target) * target_loss
        return Stage2ObjectiveOutput(
            total=total,
            source_to_target=source_loss,
            native_target=target_loss,
            source_count=source_count,
            target_count=target_count,
        )
